### ISSUE TITLE
Events werden nicht erstellt 

### ISSUE THREAD

**Issue by SilasLedoux** [cgoIT/contao-calendar-ical-bundle#10]
Hi,
Ich habe eine Frage: ich habe das Package installiert und einen Kalender im backend erstellt sowie den Google Kalender ics Link als webquelle eingefügt. Wenn ich dann auf speichern klicke kommt die Fehlermeldung: 
str_replace(): Argument #2 ($replace) must be of type array|string, null given
Wenn ich im Feld Pattern Event title etwas eingebe, kommt diese Meldung nicht - Events werden aber nicht erstellt.
Woran liegt das?

**Comment by cgoIT** [comment]
Hi,
schaue ich mir gerne an. Allerdings bräuchte ich dazu noch ein paar weitere Infos.

- deine verwendete PHP-Version
- die installierte Version dieser Erweiterung hier
- die verwendete Contao-Version
- sofern der ics-Feed öffentlich ist die URL zum Feed
- die vollständige Fehlermeldung aus dem Logfile

Dann kann ich mir das gerne einmal anschauen. Allerdings bin ich ab morgen für eine Woche im Urlaub. Kann also sein, dass es bis danach warten muss.

**Comment by SilasLedoux** [comment]
Hi,
betsen Dank. Alles klar:
- meine php Version 8.2.3
- Erweiterungsversion: cgoit/contao-calendar-ical-php8-bundle Version 4.4.8
- Contao Version 4.11.2
- ics: https://calendar.google.com/calendar/ical/c_uu2f91bb7rl4ee9uej232n95fk%40group.calendar.google.com/public/basic.ics
- Fehlermeldung: str_replace(): Argument https://github.com/cgoIT/contao-calendar-ical-bundle/pull/2 ($replace) must be of type array|string, null given
-Log im contao Backend System-log:
[18.02.2023 09:59:26] reading cal |  
[18.02.2023 09:59:26] Reload iCal Web Calendar Test1 (12): Triggered by 1676710766 - 0 = 1676710766 > 86400 |  
[18.02.2023 09:59:14] A new entry "tl_calendar.id=12" has been created
--
Oder wo finde ich noch die Fehlermeldung / Für Logs vom Server muss ich auf einen Kollegen warten und würde ich dann nachreichen.

Eilig ist es nicht, schonmal besten Dank und schönen Urlaub!

**Comment by cgoIT** [comment]
Hi,

vielen Dank. Wenn du an die Logs noch rankommst, dann super. Wenn nicht, dann kann ich das hoffentlich auch so nachstellen. Ich gebe zu, dass ich die Erweiterung noch nie unter PHP 8.2 genutzt habe. Wenn du einfach(!) die Möglichkeit hast ein Downgrade auf PHP 8.1 zu machen, dann könntest du das einmal probieren. Ggf. ist da mit 8.2 aus einer WARNING ein ERROR geworden. Ich bin da zu wenig im aktuellen PHP-Geschehen drin. ;) 
Aber es klingt nach etwas, was recht einfach zu beheben sein sollte. Kann wie gesagt nur etwas dauern. Aber ich schaue es mir an.

**Comment by cgoIT** [comment]
Hi,

ich habe mir das jetzt einmal angeschaut und kann das Problem leider nicht nachstellen. Ich habe allerdings auch die Contao-Version 4.11.9 verwendet (und eine 4.13er Version). Daher bräuchte ich doch die Logfiles von dir um zu sehen, wo der Fehler herkommt. Sorry.

**Comment by iainmacnab** [comment]
Hi,
Contao 4.13.29
PHP auf 8.1 downgraded
- .ics File Format verified
Bei Import erhalte ich folgende Fehler:
strcmp(): Argument #2 ($string2) must be of type string, int given
- muss ich irgendwas beachten. Beispiel (Dateianfang):

BEGIN:VCALENDAR
PRODID:www.commsy.net
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:8186246
DTSTAMP:20230829T112632Z
SUMMARY:Sommerferien
DESCRIPTION:
URL:https://schulintern.sh.schulcommsy.de/room/2394585/date/8186246
DTSTART:20240722
DTEND:20240830
ORGANIZER;CN=euTest:mailto:info@eu-mart.net
END:VEVENT

Danke!
Iain

**Comment by cgoIT** [comment]
Hi @iainmacnab. Ist der ICS-Feed öffentlich erreichbar? Wenn ja, kannst du mir den mal nennen. Dann würde ich mal schauen, ob ich den Fehler damit nachstellen kann.
