### ISSUE TITLE
Downloadquery not works if eventlist and eventreader site have the same alias

### ISSUE THREAD

**Issue by theDyingMountain** [cgoIT/contao-calendar-ical-bundle#11]
In my case, the alias of generated URL is the same for eventlist and reader (/meine-termine). This causes a 404 error.

**Comment by cgoIT** [comment]
Do you have a minimal example where I can reproduce the error?

**Comment by theDyingMountain** [comment]
Alles klar 🙂
- erstelle 2 Seiten, eine für die Liste und eine für den Eventreader, auf der Seite für den Eventreader muss die Checkbox "Element erforderlich" aktiv sein
- Eventlisten Module auf der ersten Seite zusammen mit dem ical Contentelement plazieren und Eventreader Module auf der anderen Seite
- Mit diesem Setup kommt es zu einem 404 Fehler bei Klick auf den Link

**Comment by cgoIT** [comment]
Ich habe das jetzt mal in einer Testinstallation (Contao-Demo mit PHP 8.1 und Version 4.4.8 dieser Erweiterung) nachgebaut. Da funktioniert alles bestens. Der Link, den er für das iCal-ContentElement generiert ist http://localhost:8888/events/ical/3/title/Download%252Bals%252BiCal.html

**Comment by theDyingMountain** [comment]
Der Fehler tritt bei mir hier auf: https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/controllers/FrontendIndex.php#L192-L195 `isset($_GET['auto_item'])` ist bei mir null.

**Comment by theDyingMountain** [comment]
Okay bei mir wurde bei Aufruf des Links, die Seite mit dem Reader zuerst geladen, anstelle der Listenseite. Wenn ich bei der Listenseite die Prioriät erhöhe funktioniert es.
