### ISSUE TITLE
Export von mehreren Kalendern funktioniert nicht aufgrund url encoding

### ISSUE THREAD

**Issue by theDyingMountain** [cgoIT/contao-calendar-ical-bundle#12]
In meinem Fall wird die URL bei zwei verwendeten Calendern folgendermaßen generiert: _ical/2%252C1/title/iCal-Datei%252Bherunterladen_. Durch die Codierung funktioniert aber preg_replace nicht (https://github.com/cgoIT/contao-calendar-ical-bundle/blob/master/src/Resources/contao/classes/ContentICal.php#L48)

Ein einfaches urldecode hat bei mir geholfen. Also `$this->getAllEvents(preg_split('/,/', urldecode(\Input::get('ical'))), $startdate, $enddate);`

**Comment by cgoIT** [comment]
Ich habe das mal entsprechend im master-Branch umgesetzt. Kannst du das bitte mal mit der Version dev-master kurz testen? Dann würde ich eine neue Version machen, wenn es geht.

**Comment by theDyingMountain** [comment]
Sorry für die späte Rückmeldung. Ich habe soeben die dev-master installiert und es funktioniert :)

**Comment by cgoIT** [comment]
Gefixed in Version 4.4.9
