### ISSUE TITLE
Hook für getAllEvents

### ISSUE THREAD

**Issue by theDyingMountain** [cgoIT/contao-calendar-ical-bundle#16]
Ich habe in meiner Installation über den getAllEvents Hook spezielle Filter für meine Events. Leider bietet der Ical Exporter keinen Hook an, um die Funktion auch hier zu übernehmen.

**Comment by theDyingMountain** [comment]
#17 hier mein Vorschlag. Evtl. gibt es eine bessere Lösung. Für meine Zwecke hat es funktioniert.

**Comment by cgoIT** [comment]
Hi, ich hatte dir vor ein paar Tagen mal einen Kommentar in dem PR hinterlassen. Bzw. eher eine Frage. Kannst du dir das mal anschauen? Dann würden wir da weiter kommen.

**Comment by theDyingMountain** [comment]
Hi, danke für die Rückmeldung. Irgendwie sehe ich aber keinen Kommentar bei dem PR? Hatte auch keine E-Mail dazu bekommen...

**Comment by cgoIT** [comment]
Hi @theDyingMountain,

sorry. Ich habe das nicht abgeschickt. Jetzt solltest du was sehen und auch eine Mail bekommen haben.

**Comment by cgoIT** [comment]
@theDyingMountain 
ich habe eben gemerged. Könntest du einmal bitte kurz mit der Version aus dem master testen (dev-master). Wenn das erfolgreich ist, dann würde ich eine neue Version veröffentlichen.

**Comment by theDyingMountain** [comment]
Wenn du nichts geändert hast, sollte es funktionieren. Ich hatte exakt den Code schon in meiner Anwendung.
