### ISSUE TITLE
Support für Contao ab 5.2

### ISSUE THREAD

**Issue by kroerig** [cgoIT/contao-calendar-ical-bundle#19]
Hallo,

wie sieht es mit Support für Contao 5.2 bzw. die kommende 5.3 aus?

**Comment by cgoIT** [comment]
Hi, der wird sicherlich kommen müssen. Eher dann für die 5.3 LTS. Allerdings kann ich aktuell noch nicht sagen, wann es soweit sein wird. Angefangen ist noch nichts. Falls hier also schon einmal jemand starten will, gerne.

**Comment by kroerig** [comment]
Meine PHP Kenntnisse reichen dafür leider nicht aus. Ich teste aber gerne mit.

**Comment by cgoIT** [comment]
Hi @kroerig,

ich habe gerade eine Version 5.0.0 veröffentlicht. Diese ist mit Contao 4.13 und Contao 5.x kompatibel. Es hat sich sehr viel geändert. Insofern würde ich gerne auf dein Angebot des Testens zurückkommen. ;)
Habe lokal sehr viel rauf und runter getestet. Aber man weiß ja nie....

**Comment by kroerig** [comment]
Hm, ich bin mir nicht sicher, ob es mit deiner Erweiterung zutun hat oder in Bug im Contao Manger 1.8.0 ist.
Die Installation läuft durch, aber der Button "Datenbank aktualisieren" schickt mich nach `/contao/install`. Aber die URL gibt es ja nicht mehr.

**Comment by kroerig** [comment]
Ne, irgendwas läuft da gehörig schief. Ich musst die Erweiterung wieder deinstallieren um den CM wieder nutzen zu können.
Contao Version 5.2.6
CM 1.8.0
PHP 8.1

**Comment by cgoIT** [comment]
Hi @kroerig,

ich sehe das Problem. Allerdings bei mir schon, wenn ich versuche einfach nur ein Contao 5 über den Manager zu installieren. From Scratch. Da will er am Ende immer die DB aktualisieren. Über die Route contao/install. Was ja unter Contao 5. nicht mehr geht. Da habe ich aber noch nicht einmal angefangen irgendwas mit irgendeiner anderen Erweiterung zu tun.
Ich nutze den Manager eigentlich nie. Ich glaube, ich bin auch einfach zu doof dazu wie sich jetzt zeigt... :S

**Comment by kroerig** [comment]
Ich kann es später mal über die CLI probieren.

**Comment by cgoIT** [comment]
Hi @kroerig,

ich habe mich jetzt mal etwas intensiver mit dem CM beschäftigt und ihr auch zum Laufen gebracht. Ich konnte nun die Erweiterung mit der Version 5.0.1 korrekt über den CM installieren.

**Comment by kroerig** [comment]
Ich probiere es später

**Comment by kroerig** [comment]
So, die Installation hat funktioniert. Konnte auch einen iCal Kalender abonnieren.
Nur der Import will nicht. Das dürfte aber am Format der Datei liegen. Ich mache da mal einen neuen Fall auf. Müssten wir mal schauen, ob wir da beim Import was machen können, oder ich mir beim Export was überlegen muss.
