### ISSUE TITLE
Issue with Date Conversion from ICS File to Contao

### ISSUE THREAD

**Issue by Webstylerin** [cgoIT/contao-calendar-ical-bundle#25]
Hello,

I am currently facing an issue with the integration of booking data for a vacation house into Contao using the cgoit/contao-calendar-ical-php8-bundle extension. The extension is generally functioning well, but there seems to be a discrepancy in how dates from the ICS file are being interpreted and displayed on the website.

Issue Description:
The ICS file contains booking events with specific start and end dates. However, when these dates are imported into Contao, there is a shift in the date range displayed.

Example:
An event in the ICS file is as follows:

```
BEGIN:VEVENT
DTSTAMP:20231214T215613Z
DTSTART;VALUE=DATE:20231217
DTEND;VALUE=DATE:20231225
SUMMARY:booking
UID:***@voffice.com
END:VEVENT
```

This event is supposed to be from 17.12.2023 to 25.12.2023. However, in Contao, initially with the timezone set to "Berlin", it was displayed as "16.12.2023–23.12.2023". After changing the timezone setting to "GMT", it changed to "17.12.2023–24.12.2023". Despite trying other timezones, I am unable to get the correct end date (25.12.2023) in Contao.

Technical Details:

- Contao version: 4.13.35
- cgoit/contao-calendar-ical-php8-bundle version: 4.5.1

I am uncertain whether this is an issue with the ICS file format or the extension's interpretation of the file. Any assistance or insight into resolving this discrepancy would be greatly appreciated.

Thank you in advance for your help!

Best regards,
Nicole

**Comment by cgoIT** [comment]
Off the top of my head, I can't immediately say what exactly the error is. There are the following possibilities:
1. wrong ICS file. The event looks good to me at first, but the rest around it would be interesting, as it also contains other things that may be of interest for date handling.
2. an error in the handling of the file after parsing. That would be my task to solve this
3. an error in the library used for parsing.

It is very possible that it is 2. 
Two questions:
1. could you please check if the error still occurs in version 5.0.2? 
2. is the ICS file or the feed public? The file or access to the feed would help me to analyze the error.

**Comment by cgoIT** [comment]
fehlendes Feedback. Daher mache ich hier mal zu.
