### ISSUE TITLE
ICAL Import from Google

### ISSUE THREAD

**Issue by spienz** [cgoIT/contao-calendar-ical-bundle#26]
Hy,

the Import from Google is working, but every Date is importet with a weblink, but this weblink is not there because Contao don't build the Event Side.
If you wan't further details ic an send you in a direct communication.

THX

Sebastian

**Comment by cgoIT** [comment]
Hi @spienz,

it would be great if you could use the bug report template. Doing so will give some more information about the concrete problem.

Cheers
