### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous

### ISSUE THREAD

**Issue by arminfrey** [cgoIT/contao-calendar-ical-bundle#39]
**To Reproduce**

install contao-calendar-ical-bundle
call url
![image](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/104427130/f3261f7e-be32-491a-b906-ce4acfc288e7)

**Expected behavior**
a functional site

**Screenshots**

**Logs**
[stacktrace.txt](https://github.com/cgoIT/contao-calendar-ical-bundle/files/14944220/stacktrace.txt)

**Configuration (please complete the following information):**

- OS: Windows11
- Browser Vivaldi
- Bundle Version 5.2.2
- PHP Version 8.1.27
- Contao Version 4.13.40

**Additional context**
I have installed the old modul (contao-calendar-ical-php8-bundle). That has worked until today (Today I have removed it and installed the contao-calendar-ical-bundle 5.2.2

**Comment by cgoIT** [comment]
Hi @arminfrey,
I've pushed some changes to the `main` branch. Is it possible for you to use version dev-main of this bundle and test if the error is fixed with those changes?

**Comment by arminfrey** [comment]
Hi @cgoIT,

the error is fixed with version dev-main.

Thank you.

**Comment by cgoIT** [comment]
Fixed in Release 5.2.3

https://github.com/cgoIT/contao-calendar-ical-bundle/pull/40#issuecomment-2049413807
