### ISSUE TITLE
[BUG] Jeder iCal-Export hat dieselbe URL

### ISSUE THREAD

**Issue by pipeman1981** [cgoIT/contao-calendar-ical-bundle#41]
Hej all,
**To Reproduce**
1. Drei Inhaltselemente vom Typ iCal erstellen und jeweils einen anderen Kalender nehmen
2. Artikel mit Inhaltselementen anzeigen
3. Alle drei Inhaltslelemente werden als Download mit plausiblen Größen angeboten, tatsächlich verweisen aber alle auf dieselbe URL https://dyckburg.de/kalender.html?ical=1

**Expected behavior**
Ich hätte erwartet, dass die URLs irgendwie generisch sind, je nachdem, welche Kalender ausgewählt wurden

**Screenshots**
![verfuegbareKalender](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/42336137/94dcf6f3-a6b5-49fd-8db5-23e950ab1c34)

**Configuration (please complete the following information):**

- OS: Windows 11, 
- Browser chrome
- Bundle Version 5.2.3]
- PHP Version 8.2.17
- Contao Version 4.13.40

Vielen Dank vorab, wenn Ihr mehr Infos braucht, meldet Euch gerne.

Gruß,

Carsten

**Comment by cgoIT** [comment]
Hi @pipeman1981,

was genau meinst du mit "generischer". Da es sich in diesem Fall um ein CE handelt, ändert sich erst einmal am Routing nichts. Die Auswahl der Kalender erfolgt rein über den Parameter `ical`.
Seit Contao 4.10 und der Version 5.2.0 dieses Bundles hier könntest du aber mal versuchen, ob du über den Seitentyp iCal das von dir gewünschte Ergebnis erzielen kannst.

lg
Carsten

**Comment by pipeman1981** [comment]
Hej Namensvetter :-)
ich meinte damit, dass egal, welchen Kalender ich auswähle, im Link immer ?ical=1 steht. Ist zurzeit freigeschaltet und unter https://dyckburg.de/kalender.html einsehbar. Im Backend sieht das wie folgt aus:
![dyckburg de_contao_do=article id=1216 table=tl_content act=edit rt=b1 QT_t8y9lVUeop7A85kkJJ05IWPY_KlqwnKLwllnnL7A Nn6XxhtdJj_A0MhXyz5jFAk5CJxUZWL-98iS_xqvZuA2W7LKSCYid8D11w ref=Bm4uPVZa](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/42336137/7541c939-36ec-47ae-99be-2f6890674805)

**Comment by cgoIT** [comment]
Hi, das ist so bis jetzt auch erst einmal "works as designed". Was ja nicht ausschließt, dass man es vielleicht ändern könnte. Wie sollten deiner Meinung nach die unterschiedlichen Links denn idealerweise aussehen?

**Comment by cgoIT** [comment]
fehlendes Feedback. Daher mache ich hier mal zu.
