### ISSUE TITLE
 Field 'ical_title' doesn't have a default value

### ISSUE THREAD

**Issue by pointout** [cgoIT/contao-calendar-ical-bundle#42]
**To Reproduce**

1. Go to 'Backend'
2. Click on 'Seitenstruktur'
3. Neue Seite anlegen
5. See error

or
1. Go to 'Backend'
2. Click on 'Artikel'
3. Artikel bearbeiten und neues Inhalstslement anlegen
5. See error

**Expected behavior**
Neue Seite sollte anlegbar sein. Stattdessen Fehlermeldung: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'ical_title' doesn't have a default value

**Logs**
Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'ical_title' doesn't have a default value" at /var/www/vhosts/hostingXXX.netcup.net/httpdocs/domain/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 114

**Configuration (please complete the following information):**

- Browser Firefox
- Bundle Version 5.2.3
- PHP Version 8.1.28
- Contao Version 4.13.43

config.yml:
```doctrine:
  dbal:
    connections:
      default:
        options:
          1002: "SET SESSION sql_mode=(SELECT CONCAT(@@sql_mode, ',TRADITIONAL'))"
```

**Comment by cgoIT** [comment]
Hi @pointout,
ich kann weder den Fehler bei den Seiten, noch bei den Inhaltselementen bei mir nachstellen. Zumal im DCA (zumindest im SQL-Teil) durchaus Defaults definiert sind. Siehe z.B. [hier](https://github.com/cgoIT/contao-calendar-ical-bundle/blob/1cc5f211ae59302290be15bfd975a77ed5719e27/contao/dca/tl_page.php#L27) und [hier](https://github.com/cgoIT/contao-calendar-ical-bundle/blob/1cc5f211ae59302290be15bfd975a77ed5719e27/contao/dca/tl_content.php#L31).

Kommst du an die vollständige Exception ran und könntest die hier bitte mal posten? Danke!

**Comment by pointout** [comment]
Hallo @cgoIT, ich poste spätestens morgen.
Ich habe gesehen, dass defaults definiert sind, die habe ich auf `text NULL ` geändert, dann hat es funktioniert. Mir ist auch aufgefallen, dass auch in den Core Bundels die Textfelder alle mit `text NULL` definiert sind.

**Comment by pointout** [comment]
Ich update gerade auf 5.2.4. Im Manager steht bei den Datenbankänderungen kein Defaultwert. Vielleicht liegt da das Problem:
![grafik](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/8960545/e1be0246-c1d5-42be-8305-0b6684688ccb)

**Comment by pointout** [comment]
Der Manager ändert die DB Struktur nicht, weil ich sie angepasst hatte. Ich habe sie manuell in phpMyAdmin wieder geändert. Wenn man den Haken bei "NULL" entfernt, steht bei "Standard" `kein(e)`. Das lässt sich auch nicht auf `''` ändern. 
![grafik](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/8960545/53ff06ce-b5db-425c-b132-5ebb10cf3f6a)

**Comment by cgoIT** [comment]
Ich bin mir nicht so ganz sicher, was du genau mit deiner Umgebung gemacht hast. Frische Installation, Erweiterung installiert und in der tl_page sieht bei mir das Feld folgendermaßen aus:

![image](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/8972203/d5f5b13d-ae20-43ec-acc7-30d4616ffacf)

Vielleicht würde es helfen, wenn du mal eine neue Testinstallation aufsetzt und dann schaust, ob dort die gleichen Probleme bei dir auftreten.

**Comment by pointout** [comment]
Ich habe jetzt am selben Server eine komplett neue und leere 4.13 Instalation und nur das "contao-calendar-ical-bundle" dazu installiert. Bei der Datenbakänderung im Manager bei der Installation:
![grafik](https://github.com/cgoIT/contao-calendar-ical-bundle/assets/8960545/1ff08458-dccd-417c-b48a-0ff90f3c93cc)
Auch hier kein Default bei `TEXT NOT NULL`.

Beim Anlegen einer Seite: `An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'ical_prefix' doesn't have a default value`

Vielleicht hängt es von der DB/Version ab. Der Hoster verwendet Server-Version: 8.0.33 - MySQL Community Server - GPL.

[https://de.contaowiki.org/Korrekte_database.sql_erzeugen](https://de.contaowiki.org/Korrekte_database.sql_erzeugen) ist zwar schon alt, aber in dem Statement Beispiel steht: ``` `text_null_demo` text NULL,```
Und auch in den core bundles ist ein Textfeld immer mit `text NULL`. Was spricht dagegen es im Plugin zu ändern (auch im SELECT Feld)?

**Comment by cgoIT** [comment]
Hi,
es scheint tatsächlich an der MySQL zu liegen (MariaDB scheint da an der Stelle anders zu ticken). Es gibt seit 2008 einen  [Feature-Request](https://bugs.mysql.com/bug.php?id=21532) für Default Werte bei text Spalten.
ich habe jetzt mal eine Version gemacht in der die Spalten NULLable sind und die entsprechenden Anpassungen im Code gemacht, um mit Null-Werte umgehen zu können. Hoffentlich funktioniert es jetzt.

**Comment by pointout** [comment]
Danke! Die Erzeugung der ical Inhaltselemente hat auch schon ohne weiterer Codeänderungen funktioniert gehabt. Ich update und teste sobald die neue Version da ist.

**Comment by cgoIT** [comment]
Hi,

ist schon da: https://github.com/cgoIT/contao-calendar-ical-bundle/releases/tag/v5.2.5

**Comment by pointout** [comment]
Nochmals Danke. Installation lief ohne DB Änderungen durch, die ich ja schon manuell gemacht hatte und ical Inhalteselemente funktionieren. Keine Fehlermeldung beim Anlegen von Inhaltselementen.

**Comment by cgoIT** [comment]
Danke für die Rückmeldung. Dann mache ich hier mal zu.
