### ISSUE TITLE
Wunsch: Datenimport per Cron im Hintergrund

### ISSUE THREAD

**Issue by kroerig** [cgoIT/contao-calendar-ical-bundle#52]
Bei sehr großen Kalendern dauert der Import von einer URL recht lange. Das blockiert dann den Seitenaufruf.
Da wäre es hilfreich, wenn der Import regelmäßig im Hintergrund laufen könnte.

**Comment by cgoIT** [comment]
Hi @kroerig,

kannst du nicht die URL per normalem Cronjob aufrufen? Via cURL oder wget z.B.. Oder über einen Dienst wie [cron-job.org](https://cron-job.org/de/).

**Comment by kroerig** [comment]
welche URL soll ich denn aufrufen? Gib es eine URL die den Import anstößt?
Dafür hat Contao ja die internen Crons.

**Comment by cgoIT** [comment]
> welche URL soll ich denn aufrufen?
Eine URL zu einer Seite, auf der der Kalender eingebunden ist.
