### ISSUE TITLE
[BUG] Logfile enthält Fehlereinträge, es scheint aber alles zu funktionieren

### ISSUE THREAD

**Issue by mlirsch** [cgoIT/contao-calendar-ical-bundle#55]
**To Reproduce**

1. Frische Contao Official Demo 5.3.13 installation
2. cgoit/contao-calendar-ical-bundle Version 5.3.4 installiert
3. Im Backend unter Events ein iCal Abonnement erstellen
4. Die ics-Datei wird korrekt im /public/share Ordner erstellt, im logfile unter /var/logs werden mehrere Einträge u.a. mit ERROR-Meldungen erstellt
5. Auch beim Import aus einer iCal Web-Datenquelle werden alle Termine korrekt im Kalender hinzugefügt, jedoch kommen auch im log file mehrere Einträge hinzu
6. Im Backend System-Log wird kein Fehler angezeigt

**Expected behavior**
Einträge im Logfile unter /var/logs nur bei Fehlern erstellen

**Configuration (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Firefox 130.0
- PHP Version 8.1.2
- Contao Version 5.3.13

[prod-2024-09-06.log](https://github.com/user-attachments/files/16906127/prod-2024-09-06.log)

**Comment by cgoIT** [comment]
Sollte in Version 5.3.5 behoben sein

**Comment by mlirsch** [comment]
Perfekt, danke für die rasche Bearbeitung.
