### ISSUE TITLE
[ENHANCEMENT] Handling of recurrent events with UNTIL date

### ISSUE THREAD

**Issue by johannes-bittner** [cgoIT/contao-calendar-ical-bundle#61]
**Ich importiere einen Google-Kalender per ics-Datei, der zahlreiche Termine mit Wiederholungen enthält, Bsp.:**
```

BEGIN:VEVENT
DTSTART;VALUE=DATE:20250324
DTEND;VALUE=DATE:20250329
RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20250411;BYDAY=MO
DTSTAMP:20241127T081232Z
UID:XXXXX@google.com
CREATED:20241105T084704Z
LAST-MODIFIED:20241105T084704Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:TERMINTITEL
TRANSP:TRANSPARENT
END:VEVENT
```

**Ansicht im Google-Kalender:** 
![grafik](https://github.com/user-attachments/assets/702c18c4-0f3c-476f-be0b-a36702237b6f)

**Ansicht Daten in Contao:** 
![grafik](https://github.com/user-attachments/assets/642a31a4-03f1-423a-b288-d9e3948a8e53)

**Ansicht Wiederholungseinstellungen in Contao:** 
![grafik](https://github.com/user-attachments/assets/c695a1de-39a9-49b7-b75f-fb1a06e5a0b4)

Die "0" dürfte an dieser Stelle dazu führen, dass das Event ad infinitum wiederholt wird (was bei der betroffenen Contao-Installation das Jahr 2106 ist ;-)), weil die Beschränkung der Wiederholung auf ein bestimmtes Datum (wie im Google-Kalender) damit ja nicht korrekt abgebildet wird. Lässt sich das überhaupt korrekt abbilden? => im Beispiel würde das ja bedeuten, dass in Contao als Wiederholungsanzahl "2" eingegeben werden müsste (was beim Import allerdings über das angegebene Datum bei UNTIL berechnet werden müsste) - oder lässt sich das in der Form dann nicht korrekt importieren?

**Comment by cgoIT** [comment]
Hi,
deine Annahme ist richtig. Aktuell geht das so nicht bzw. wird nicht unterstützt. Ich habe gerade mal in den Code geschaut. Das wäre auch nicht so einfach zu lösen. Man könnte jetzt natürlich versuchen die Anzahl aus dem Datum heraus zu berechnen. Das dürfte möglich sein. Ist aber natürlich etwas Aufwand und leider ist es bei mir aktuell mit der Zeit nicht so super.

Ich lasse das hier auf jeden Fall mal auf und schaue es mir bei Gelegenheit an. Aber ich kann dir noch keinen Zeitrahmen nennen, wann ich dazu kommen werde.

**Comment by cgoIT** [comment]
Ich wollte damit nicht sagen, dass es unsinnig ist Termine in dieser Art und Weise anzulegen. Das ist in meinen Augen total valide. Ich muss nur mal in mich gehen, wie ich das am besten und saubersten lösen kann.

**Comment by cgoIT** [comment]
Hi, ich habe im main branch mal eine Version zur Verfügung gestellt, die mit einem UNTIL-Date bei Wiederholungen umgehen können sollte. Leider komme ich im Moment nicht wirklich dazu, dass zu testen. Wäre es möglich, dass du das mal mit der Version aus dem main ("dev-main") mal bei dir testest und schaust, ob das geht und dadurch auch nicht maßgeblich was anderes kaputt gegangen ist?

**Comment by johannes-bittner** [comment]
Wow, vielen Dank für diese rasche Initiative! Ich habe es inzwischen testen können und habe nur ein Problem festgestellt, dass das Handling von Wiederholungen nicht korrekt funktioniert, wenn eine Wiederholung angegeben ist, das UNTIL-Datum aber VOR dem Event-Datum liegt, was nicht abgefangen wird. Auf der anderen Seite handelt es sich dabei ja eigentlich um einen Fehler beim User-Input (auch wenn man so eine Kombination im Google-Kalender eintragen kann). 

Noch etwas ist mir aufgefallen (kann ich auch als separates Ticket anlegen): Termine, die außerhalb des Start-/Enddatums der ics-Datenquelle liegen, werden dennoch importiert und dementsprechend auch im Frontend ausgegeben.

**Comment by cgoIT** [comment]
Hi, danke für den Test. Das mit dem UNTIL-Datum vor dem Startdatum kann man sicherlich noch abfangen. Spannend, dass man so etwas überhaupt erfassen kann. Aber gut...

Bezieht sich das andere auf wiederkehrende Termine oder einzelne Termine? Wenn ersteres dann würde ich das nur als Fehler ansehen, wenn das erste Startdatum außerhalb von Start-/Ende ics Import liegt. Bei letzterem wäre es auf jeden Fall ein neues Ticket. Wobei ich mich frage, für was der Vorentwickler dieses Start-/Ende-Datum beim ics Import überhaupt eingeführt hat. Ich persönlich habe das noch nie genutzt. Und kann mir um ehrlich zu sein auch noch nicht so wirklich einen UseCase dafür vorstellen.

**Comment by cgoIT** [comment]
Hi @johannes-bittner,
der Fall UNTIL-Date < Event Startdate ist nun im master gefixed. In dem Fall wird das Event nicht mehr wiederholt.

**Comment by cgoIT** [comment]
@johannes-bittner 
ich habe für die UNTIL-Date Thematik jetzt einmal ein Release gemacht. Das andere bitte noch mal als extra Issue. Danke dir!
