### ISSUE TITLE
ics Import schreibt falschen Wert in Datenbank

### ISSUE THREAD

**Issue by mlirsch** [cgoIT/contao-calendar-ical-bundle#7]
Contao 4.13, PHP 8.1, cgoit/contao-calendar-ical-php8-bundle 4.4.5

Beim Import eines ics-Kalenders (egal ob als Datei oder Webkalender) wird in der Tabelle tl_calendar_events im Feld singleSRC statt NULL der Wert 0x0000 eingetragen. Contao versucht, die Datei zu finden und überflutet das System-Log mit der Fehlermeldung "Image "%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00" could not be processed: Image "" could not be found"

**Comment by cgoIT** [comment]
Hi, das muss ich mir einmal ansehen. Ist mir bis jetzt noch nie aufgefallen. Passiert das mit wirklich jedem ics Feed oder nur manchmal? Wenn nur manchmal: hättest du einen Beispiel-Feed für mich?

**Comment by mlirsch** [comment]
Das tritt bei mir bei jeder ics Datei auf.

**Comment by cgoIT** [comment]
Hi, ich habe mal in der Version dev-master einen Fix eingebaut. Könntest du bitte mal testen, ob das Problem damit behoben ist?

**Comment by mlirsch** [comment]
Funktioniert perfekt. Danke. Ich habe jetzt keine Einträge mehr im System-Log. 
Das Verhalten trat auch nur in Kombination mit der Eventanzeige im Mate Theme auf. In der official Demo konnte ich es nicht reproduzieren.

**Comment by cgoIT** [comment]
Sehr gut. Ich habe gerade die Version 4.4.6 online gestellt und würde das Ticket hier damit zu machen.
