### ISSUE TITLE
Commandline option

### ISSUE THREAD

**Issue by leon1995** [cgoIT/contao-calendar-ical-bundle#9]
Hi,

is there a option to import a .ics file via the commandline? This would make it possible to automatically update the calendar when the ics file has changed.

EDIT: I noticed that importing the ics file twice will duplicate all events instead of updating them. Is there a way to be able to update vents based on the ics file?

**Comment by cgoIT** [comment]
Hi,

currently there is no cli interface planned. Maybe this could be done in the (far) future.
Regarding your second question: If you import the events via an "iCal web source" all events in the calendar are deleted before the import. So the equivalent behavior during the import of a local ics file would be to check the "Remove existing events" checkbox.

To have your events updated automatically maybe you could provide your ics file via a (local) webserver and use the "iCal web source" option with an appropriate "Calendar cache in seconds" value.
